Repository WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC, pull requests merged in 2022-10, with the labels that each got.

#1 initialisation
  .husky/pre-commit
  index.html
  package.json
  postcss.config.cjs
  public/icon.png
  public/vite.svg
  src/App.jsx
  src/components/.gitignore
  src/main.css
  tailwind.config.cjs
  vite.config.js
  yarn.lock
Labels: Reviewed

#2 Feature navbar
  package.json
  src/App.css
  src/App.jsx
  src/components/navbar/Navbar.jsx
  src/main.jsx
  tailwind.config.cjs
  yarn.lock
Labels: Ready 2 Merge

#3 Feature learning add interactive map
  package.json
  public/mapGeometry.json
  src/components/map/Map.jsx
  src/pages/Learn.jsx
  tailwind.config.cjs
  yarn.lock
Labels: Conflict solved, Ready 2 Merge

#5 Add Page How To Play
  package.json
  src/components/howToPlay/HowToPlay.jsx
  tailwind.config.cjs
  yarn.lock
Labels: Conflict solved

#13 addd questio non play
  src/pages/Quiz.jsx
Labels: Reviewed

#14 Add search for countries
  src/components/map/Map.jsx
  src/components/searchLearn/SearchLearn.jsx
  src/pages/Learn.jsx
Labels: Reviewed

#16 Feature/ country details
  src/components/annotation/Annotation.jsx
  src/components/map/Map.jsx
  src/pages/Learn.jsx
Labels: Sylvain

#19 add country details to search result and color change on click
  src/components/map/Map.jsx
  src/pages/Learn.jsx
Labels: Review needed, Conflict solved

#21 Feature/ answer question
  src/components/answer/Answer.jsx
  src/components/question/Question.jsx
  src/pages/Quiz.jsx
Labels: Conflict solved

#28 Prevent click between confirmation new question
  src/components/map/Map.jsx
  src/components/question/Question.jsx
  src/pages/Quiz.jsx
Labels: Conflict solved

#25 Features/ gamemode choice
  src/components/question/Question.jsx
  src/components/rules/Rules.jsx
  src/pages/Quiz.jsx
Labels: Sylvain, Correction done

#39 Answer feature v2.0
  src/components/answer/Answer.jsx
  src/components/question/Question.jsx
  src/pages/Quiz.jsx
Labels: Conflict solved

#40 Style/map quizz and learn
  public/blurry-white-blue.jpg
  src/App.css
  src/components/map/Map.jsx
  src/pages/Learn.jsx
  src/pages/Quiz.jsx
Labels: Conflict solved

#48 fix/marker_learn
  src/pages/Learn.jsx
Labels: Correction done

#56 about
  src/App.jsx
  src/pages/About.jsx
Labels: Sylvain

#38 Feature/recap game
  src/components/recapGame/RecapGame.jsx
  src/pages/Quiz.jsx
Labels: Correction done

#64 Feature/zoom on map
  package.json
  src/components/map/Map.jsx
  yarn.lock
Labels: Correction done

#63 Learn/ details population
  src/components/annotation/Annotation.jsx
Labels: Correction done

#70 add background video but no good size and firebase is bad
  public/imgHome.png
  public/img_video2.png
  public/img_video3.png
  public/img_video4.png
  src/components/result/Result.jsx
  src/components/rules/Rules.jsx
  src/pages/About.jsx
  src/pages/Home.jsx
  src/pages/Learn.jsx
  src/pages/Quiz.jsx
  yarn.lock
Labels: Conflict solved

#71 Feature/timer on quiz
  src/components/quizTimer/QuizTimer.jsx
  src/components/result/Result.jsx
  src/pages/Quiz.jsx
Labels: Correction done, Conflict solved

#75 video good size but need to add padding everywhere issous
  src/components/navbar/Navbar.jsx
  src/components/result/Result.jsx
  src/components/rules/Rules.jsx
  src/pages/About.jsx
  src/pages/Home.jsx
  src/pages/Learn.jsx
  src/pages/Quiz.jsx
Labels: Conflict solved

#79 Fix/spacings and nav
  src/components/navbar/Navbar.jsx
  src/components/rules/Rules.jsx
  src/pages/Home.jsx
  src/pages/HowToPlay.jsx
  src/pages/Learn.jsx
  src/pages/Quiz.jsx
Labels: Conflict solved

#82 scroll and front
  src/components/result/Result.jsx
Labels: Conflict solved

#83 add base on links for build
  public/blurry-white-blue.jpg
  public/imgHome.png
  public/img_video2.png
  public/img_video3.png
  public/img_video4.png
  public/question.png
  src/components/map/Map.jsx
  src/components/navbar/Navbar.jsx
  src/main.jsx
  src/pages/HowToPlay.jsx
Labels: Conflict solved

#87 Feature/timer for each question
  src/components/quizTimer/QuizTimer.jsx
  src/components/result/Result.jsx
  src/helpers/readableTimer.js
  src/pages/Quiz.jsx
Labels: Correction done

#90 LEARN Add response done in the recap game
  .gitignore
  src/components/detailAnswer/DetailAnswer.jsx
  src/components/recapGame/RecapGame.jsx
  src/pages/Quiz.jsx
Labels: Correction done, Conflict solved

#95 add zoom in, zoom out and center button on map
  src/components/map/Map.jsx
  src/components/map/map.css
Labels: Sylvain
