Repository WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC, pull requests merged in 2022-11, with the labels that each got.

#107 Change placeholder : Country name or capitale
  src/components/searchLearn/SearchLearn.jsx
Labels: Correction done

#110 error 404
  public/blackhole.jpg
  src/App.jsx
  src/components/notFound/NotFound.jsx
Labels: Correction done

#137 fixed poster link and icon in navbar
  src/components/navbar/Navbar.jsx
  src/components/result/Result.jsx
  src/pages/Home.jsx
  src/pages/HowToPlay.jsx
  src/pages/Learn.jsx
  src/pages/Quiz.jsx
Labels: Review needed, Conflict solved

#147 Release/v1.0
  src/components/annotation/Annotation.jsx
  src/components/question/Question.jsx
  src/components/searchLearn/SearchLearn.jsx
  src/pages/Quiz.jsx
Labels: Review needed
